name: Benchmark v20

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  bench:
    # runs-on: ubuntu-latest
    runs-on: self-hosted
    outputs:
      BENCH-N: ${{ steps.benchmark.outputs.BENCH_RESULT20_0_0 }}

    strategy:
      matrix:
        node-version: [20.0.0]

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install
        run: |
          npm install

      - name: Run tests
        id: benchmark
        run: |
          version=$(node -v | sed "s/v//g" | sed "s/\./_/g")
          node bin.js > ./bench-result.md
          # https://trstringer.com/github-actions-multiline-strings/
          result=$(cat ./bench-result.md)
          result="${result//'%'/'%25'}"
          result="${result//$'\n'/'%0A'}"
          result="${result//$'\r'/'%0D'}"
          result="${result//$'`'/'\`'}"
          echo "::set-output name=BENCH_RESULT$version::$result"

  commit:
    runs-on: ubuntu-latest
    needs: [bench]

    steps:
      - uses: actions/checkout@v3

      - name: Create Result files
        run: |
          rm -rf v20/RESULTS-v20*;
          # echo "${{ needs.bench.outputs.BENCH-N3 }}" > RESULTS-v19.md;
          # echo "${{ needs.bench.outputs.BENCH-N1 }}" > v19/RESULTS-v19_8_0.md;
          # echo "${{ needs.bench.outputs.BENCH-N2 }}" > v19/RESULTS-v19_8_1.md;
          # echo "${{ needs.bench.outputs.BENCH-N3 }}" > v19/RESULTS-v19_9_0.md;
          echo "${{ needs.bench.outputs.BENCH-N }}" > v20/RESULTS-v20_0_0.md;
          echo "${{ needs.bench.outputs.BENCH-N }}" > RESULTS-v20.md;

      - name: commit and push updated results
        uses: github-actions-x/commit@v2.9
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          push-branch: 'main'
          commit-message: 'chore(v20.x): update benchmark results'
          force-add: 'true'
          rebase: 'true'
          files: RESULTS*.md v20/*
          name: Github Actions

